# Generated by Django 6.0.1 on 2026-01-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_client_phone_ticket_device_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="client_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="device_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
