# Generated by Django 6.0.1 on 2026-01-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "tickets",
            "0003_alter_ticket_client_phone_alter_ticket_device_model_and_more",
        ),
    ]

    operations = []
