# Generated by Django 6.0.1 on 2026-01-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_ticket_tracking_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="tracking_id",
            field=models.CharField(
                blank=True, editable=False, max_length=12, null=True, unique=True
            ),
        ),
    ]
