# Generated by Django 5.2.10 on 2026-01-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_agreement_pdf_ticket_agreement_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='agreement_sent_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting Client Approval'), ('approved', 'Approved'), ('closed', 'Closed')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tracking_id',
            field=models.CharField(blank=True, default=1, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
