# Generated by Django 5.2.10 on 2026-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticket_agreement_sent_at_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tracking_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
