# Generated by Django 6.0.1 on 2026-01-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="client_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ticket",
            name="device_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="ticket",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ticket",
            name="estimated_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
