# Generated by Django 6.0.1 on 2026-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_force_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="tracking_id",
            field=models.CharField(
                default=1, editable=False, max_length=12, unique=True
            ),
            preserve_default=False,
        ),
    ]
