# Generated by Django 6.0.1 on 2026-01-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_alter_ticket_tracking_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="agreement_pdf",
            field=models.FileField(blank=True, null=True, upload_to="agreements/"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="agreement_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="client_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("awaiting_approval", "Awaiting Client Approval"),
                    ("approved", "Approved by Client"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
